name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."  # root of repo

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build Astro site
        run: npx astro build --site "https://greenorbit.space"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Add .nojekyll and CNAME
        run: |
          touch ${{ env.BUILD_PATH }}/dist/.nojekyll
          echo "greenorbit.space" > ${{ env.BUILD_PATH }}/dist/CNAME

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output deployed site URL
        run: echo "Site deployed at ${{ steps.deployment.outputs.page_url }}"